
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘7.0’

target :JWCore do
pod 'Reachability'
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'MJRefresh'
pod 'FMDB', '~> 2.6.2'
pod 'SDWebImage', '~> 3.7.5'
pod 'MJExtension'
pod 'RegexKitLite'
pod 'UMengAnalytics'
pod 'Masonry'
pod 'ICTKit'
pod 'Hyphenate_CN'
pod 'UICountingLabel','~> 1.2.0'

#pod 'PNChart'

pod 'AMapLocation'  #定位 SDK

# 主模块(必须)
pod 'ShareSDK3'
# Mob 公共库(必须)
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
end

